variable "default_region" {}
variable "cluster_name" {}
variable "kube_version" {}
variable "ami_type" {}
variable "cluster_autoscaler_version" {}
variable "web_ssh_key" {}
variable "node_pool_config_name" {}
variable "node_pool_config_disk_size_gb" {}
variable "node_pool_config_machine_type" {}
variable "node_pool_config_min_node_count" {}
variable "node_pool_config_max_node_count" {}
variable "node_pool_config_capacity_type" {}
variable "node_pool_config_purpose" {}
variable "control_plane_log_types" {}
variable "number_of_zones" {}
variable "scale_down_delay" {}
variable "scale_down_unready" {}
variable "vpc_id" {}
variable "availability_zones" {}
variable "network_ipv4_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
